### ISSUE TITLE
Export just vertices in OBJ?

### ISSUE THREAD

**Issue by heaversm** [roymacdonald/kinectToTexturedOBJ#3]
Hi - If I wanted to modify this to export just vertices, not the mesh or material, where would be the best place to start with that?

**Comment by roymacdonald** [comment]
in DepthToObjExporter.h comment from line
https://github.com/roymacdonald/kinectToTexturedOBJ/blob/master/src/DepthToObjExporter.h#L70
to
https://github.com/roymacdonald/kinectToTexturedOBJ/blob/master/src/DepthToObjExporter.h#L102

and from

https://github.com/roymacdonald/kinectToTexturedOBJ/blob/master/src/DepthToObjExporter.h#L106
to
https://github.com/roymacdonald/kinectToTexturedOBJ/blob/master/src/DepthToObjExporter.h#L127

**Comment by heaversm** [comment]
That worked great, thanks!
